### ISSUE TITLE
Можешь ли ты создать скрипт для открытия ончейн-игры в веб-браузере или её отображения на рабочем столе

### ISSUE THREAD

**Issue by Himura27** [mudachyo/MemeFi-Coin#1]
Можешь ли ты создать скрипт для открытия ончейн-игры в веб-браузере или её отображения на рабочем столе

https://t.me/onchaincoin_bot?start=user_2010875703
this link bot airdrop 

thank you

**Comment by mudachyo** [comment]
You can just open the game via web telegram in your browser, press f12, then ctrl + shift+ m, select some mobile device, and refresh the page
![image](https://github.com/mudachyo/MemeFi-Coin/assets/25475399/08fdccb5-d7ef-46d5-b40f-16993333d9cc)
![image](https://github.com/mudachyo/MemeFi-Coin/assets/25475399/af81e5fc-e182-4138-8eb0-aacf78e0337d)
