### ISSUE TITLE
excute fail

### ISSUE THREAD

**Issue by zxw523656718** [mudachyo/MemeFi-Coin#16]
![image](https://github.com/user-attachments/assets/f7f8fe40-26ea-4311-997b-fd2f85ed24d0)
excute fail

**Comment by edodo0003** [comment]
Не удалось установить соединение
Добавили боссов , нужно линку обновить ) 
Спасибо ))

**Comment by mudachyo** [comment]
> Не удалось установить соединение Добавили боссов , нужно линку обновить ) Спасибо ))

Исправил
