### ISSUE TITLE
Turbo Boost

### ISSUE THREAD

**Issue by Gerik13** [mudachyo/MemeFi-Coin#21]
1) Перестал работать турбо буст в хроме. Вместо нажатия кнопки "Включить бустер" появляется окно покупки.
![image](https://github.com/user-attachments/assets/4f102176-178c-43f9-bf74-6c317cbd4566)

2) Как побороть "Слишком много запросов. Попробуйте позже."?
Я так понимаю слишком быстро крутит бусты, после этого появляется ошибка. 
В какой строке можно скорость турбо бустов подкрутить?
![2024-11-06_14-03-45](https://github.com/user-attachments/assets/38df2f3e-ed97-49da-ae3f-76cc41b5d74f)

**Comment by mudachyo** [comment]
1. Исправил
2. Не в скрипте проблема
