### ISSUE TITLE
Не поключаеться к файлу memefi

### ISSUE THREAD

**Issue by furzich2015** [mudachyo/MemeFi-Coin#7]
![image](https://github.com/user-attachments/assets/b4182a81-0b16-4865-9c51-f2415d807301)
Как исправить? Я с Украини, и скорее всего у меня ограничения через локацию.

**Comment by furzich2015** [comment]
Update: проблема в IPv6

**Comment by mudachyo** [comment]
Не знаю чем вам помочь

Отправлено с iPhone
